#include "print.h"
#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_split_4x6_5(LCTL(KC_TAB), KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, RCS(KC_TAB), KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, LT(4, KC_BSLS), LSFT_T(KC_UP), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, LT(2, KC_LEFT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, RSFT_T(KC_RIGHT), LSFT_T(KC_UNDS), LT(3, KC_LPRN), LCTL_T(KC_LCBR), LT(2, KC_RCBR), RALT_T(KC_RPRN), LT(4, KC_TAB), KC_BSPC, LGUI_T(KC_SPC), RCTL_T(KC_ENT), KC_SPC),
//                                                               [1] = LAYOUT_split_4x6_5(KC_TRNS, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_COMM, KC_P7, KC_P8, KC_P9, KC_MINS, KC_PMNS, KC_TRNS, KC_TRNS, KC_LBRC, KC_RBRC, KC_TRNS, KC_DOWN, KC_PMNS, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_ASTR, KC_TRNS, KC_TRNS, KC_LT, KC_PEQL, KC_GT, KC_UNDS, KC_DOT, KC_P1, KC_P2, KC_P3, KC_SLSH, MO(4), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_SPC, KC_TRNS, KC_TRNS, KC_COMM, KC_P0),
//                                                               [2] = LAYOUT_split_4x6_5(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, DB_TOGG, KC_TRNS, RGB_RMOD, RGB_TOG, RGB_MOD, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, QK_BOOT, KC_TRNS, KC_LPRN, KC_RPRN, KC_MPRV, KC_MPLY, KC_MNXT, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_VOLU, KC_UP, KC_TRNS, KC_LCTL, KC_LALT, KC_LGUI, KC_GT, KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD, KC_DOWN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
//                                                               [3] = LAYOUT_split_4x6_5(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_QUES, KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_TILD, KC_PPLS, KC_P7, KC_P8, KC_P9, KC_PAST, KC_TRNS, KC_PIPE, KC_DLR, KC_CIRC, KC_AMPR, KC_ASTR, KC_PEQL, KC_PMNS, KC_P4, KC_P5, KC_P6, KC_PSLS, KC_PEQL, KC_TRNS, KC_MINS, KC_PLUS, KC_LPRN, KC_RPRN, KC_UNDS, KC_COMM, KC_P1, KC_P2, KC_P3, KC_PDOT, KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS, LT(2, KC_BSPC), KC_TRNS, KC_P0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
//                                                               [4] = LAYOUT_split_4x6_5(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_QUES, KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSLS, KC_PIPE, KC_DLR, KC_CIRC, KC_AMPR, KC_ASTR, KC_EQL, KC_LT, KC_PEQL, KC_GT, KC_LBRC, KC_RBRC, KC_DOWN, KC_TRNS, KC_MINS, KC_PLUS, KC_LPRN, KC_RPRN, KC_UNDS, KC_COMM, KC_PERC, KC_COLN, KC_LCBR, KC_RCBR, KC_TRNS, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_4x6_5(LCTL_T(KC_NO), KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, RSFT_T(KC_RGHT), KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, RCTL_T(KC_BSLS), LSFT_T(KC_UP), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, LT(2,KC_LEFT), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, LT(1,KC_RGUI), LSFT_T(KC_UNDS), LT(3,KC_LPRN), LCTL_T(KC_LNG1), LT(2,KC_LNG2), RALT_T(KC_RPRN), LT(4,KC_TAB), KC_BSPC, LGUI_T(KC_SPC), RCTL_T(KC_ENT), KC_SPC),
	[1] = LAYOUT_split_4x6_5(KC_TRNS, KC_INT1, KC_INT2, KC_INT3, KC_INT4, KC_INT5, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LNG1, KC_LNG2, KC_PSCR, KC_SCRL, KC_PAUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_INS, KC_HOME, KC_PGUP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_END, KC_PGDN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT_split_4x6_5(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, DB_TOGG, KC_TRNS, RGB_RMOD, RGB_TOG, RGB_MOD, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, QK_BOOT, KC_TRNS, KC_LPRN, KC_RPRN, KC_MPRV, KC_MPLY, KC_MNXT, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_VOLU, KC_UP, KC_TRNS, KC_LCTL, KC_LALT, KC_LGUI, KC_GT, KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD, KC_DOWN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_split_4x6_5(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_QUES, KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_TILD, KC_PPLS, KC_P7, KC_P8, KC_P9, KC_PAST, KC_TRNS, KC_PIPE, KC_DLR, KC_CIRC, KC_AMPR, KC_ASTR, KC_PEQL, KC_PMNS, KC_P4, KC_P5, KC_P6, KC_PSLS, KC_PEQL, KC_TRNS, KC_MINS, KC_PLUS, KC_LPRN, KC_RPRN, KC_UNDS, KC_COMM, KC_P1, KC_P2, KC_P3, KC_PDOT, KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS, LT(2,KC_BSPC), KC_TRNS, KC_P0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[4] = LAYOUT_split_4x6_5(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_QUES, KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSLS, KC_PIPE, KC_DLR, KC_CIRC, KC_AMPR, KC_ASTR, KC_EQL, KC_LT, KC_PEQL, KC_GT, KC_LBRC, KC_RBRC, KC_DOWN, KC_TRNS, KC_MINS, KC_PLUS, KC_LPRN, KC_RPRN, KC_UNDS, KC_COMM, KC_PERC, KC_COLN, KC_LCBR, KC_RCBR, KC_TRNS, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};
#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

bool get_hold_on_other_key_press(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LSFT_T(KC_UNDS):
            return true;
        case LT(4, KC_TAB):
            return true;
        case LT(2, KC_TAB):
            return true;
        case LGUI_T(KC_SPC):
            return true;
        case LSFT_T(KC_UP):
            return true;
        case RCTL_T(KC_ENT):
            return true;
        default:
            // Do not select the hold action when another key is pressed.
            return false;
    }
}

uint8_t mod_state;
bool    process_record_user(uint16_t keycode, keyrecord_t *record) {
#ifdef CONSOLE_ENABLE
    uprintf("KL: kc: 0x%04X, col: %2u, row: %2u, pressed: %u, time: %5u, int: %u, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, record->tap.interrupted, record->tap.count);
    uprintf("mod %2u: ", get_mods());
    uprintf("shift mod mask: %2u", MOD_MASK_SHIFT);
    uprintf("mod == shift: %u\n", get_mods() & MOD_MASK_SHIFT);
#endif
    switch (keycode) {
        case LCTL_T(KC_NO):
            if (record->tap.count && record->event.pressed) {
                tap_code16(C(KC_SPC));
                return false;
            }
            break;
        case LSFT_T(KC_UNDS):
            if (record->tap.count && record->event.pressed) {
                tap_code16(KC_UNDS);
                return false;
            }
            break;
        case LT(3, KC_LPRN):
            if (record->tap.count && record->event.pressed) {
                tap_code16(KC_LPRN);
                return false;
            }
            break;
        case LCTL_T(KC_LCBR):
            if (record->tap.count && record->event.pressed) {
                mod_state = get_mods();
                if (mod_state & MOD_MASK_SHIFT) {
                    del_mods(MOD_MASK_SHIFT);
                    tap_code16(KC_LBRC);
                    set_mods(mod_state);
                } else {
                    tap_code16(KC_LCBR);
                }
                return false;
            }
            break;
        case LT(2, KC_RCBR):
            if (record->tap.count && record->event.pressed) {
                mod_state = get_mods();
                if (mod_state & MOD_MASK_SHIFT) {
                    del_mods(MOD_MASK_SHIFT);
                    tap_code16(KC_RBRC);
                    set_mods(mod_state);
                } else {
                    tap_code16(KC_RCBR);
                }
                return false;
            }
            break;

        case LCTL_T(KC_COLN):
            if (record->tap.count && record->event.pressed) {
                tap_code16(KC_COLN);
                return false;
            }
            break;
        case LT(2, KC_DQUO):
            if (record->tap.count && record->event.pressed) {
                tap_code16(KC_DQUO);
                return false;
            }
            break;
        case RALT_T(KC_RPRN):
            if (record->tap.count && record->event.pressed) {
                mod_state = get_mods();
                if (mod_state & MOD_MASK_SHIFT) {
                    tap_code16(KC_QUOT);
                } else {
                    tap_code16(KC_RPRN);
                }
                return false;
            }
            break;
        case LT(3, KC_UNDS):
            if (record->tap.count && record->event.pressed) {
                tap_code16(KC_UNDS);
                return false;
            }
            break;
    }
    return true;
}

const key_override_t ignore_shift_l     = ko_make_with_layers(MOD_MASK_SHIFT, KC_GRV, KC_GRV, 4);
const key_override_t ignore_shift_comma = ko_make_with_layers(MOD_MASK_SHIFT, KC_COMM, KC_COMM, 3);
const key_override_t reverse_shift_lcbr = ko_make_basic(MOD_MASK_SHIFT, LCTL_T(KC_LCBR), KC_LBRC);
const key_override_t reverse_shift_rcbr = ko_make_basic(MOD_MASK_SHIFT, LT(2, KC_RCBR), KC_RBRC);
// following line doesn't work. need to use process_record_user function instead
const key_override_t   shift_to_dquote = ko_make_basic(MOD_MASK_SHIFT, RALT_T(KC_RPRN), KC_DQUO);
const key_override_t **key_overrides   = (const key_override_t *[]){
    &ignore_shift_l,
    &ignore_shift_comma,
    &reverse_shift_lcbr,
    &reverse_shift_rcbr,
    &shift_to_dquote,
    NULL // Null terminate the array of overrides!
};

uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LCTL_T(KC_LCBR):
            return TAPPING_TERM + 500;
        case LT(2, KC_RCBR):
            return TAPPING_TERM + 500;
        case LT(3, KC_LPRN):
            return TAPPING_TERM + 500;
        case RALT_T(KC_RPRN):
            return TAPPING_TERM + 500;
        default:
            return TAPPING_TERM;
    }
}
uint16_t get_quick_tap_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LALT_T(KC_ESC):
            return 0;
        case LT(4, KC_BSLS):
            return 0;
        case LSFT_T(KC_PEQL):
            return 0;
        case LT(2, KC_TAB):
            return 0;
        case LSFT_T(KC_UNDS):
            return 0;
        case LT(3, KC_LPRN):
            return 0;
        case LCTL_T(KC_COLN):
            return 0;
        case LT(2, KC_DQUO):
            return 0;
        case RALT_T(KC_RPRN):
            return 0;
        case LT(4, KC_TAB):
            return 0;
        case LT(4, KC_ENT):
            return 0;
        default:
            return QUICK_TAP_TERM;
    }
}
